services:
  jupyter:
    image: jupyter/base-notebook:latest
    ports:
      - 8888:8888
    volumes:
      - ./notebook:/home/jovyan/work
    command:
      - start-notebook.sh
      - --NotebookApp.token='' # 認証を無効化
      - --NotebookApp.disable_check_xsrf=True # CSRFチェックを無効化
